README.md, commands/setup.go, main.go, resources/linux-gnome-setup-runner.sh, resources/osx-setup-runner.sh
Added the command for easy setup and included scripts on `/resources` for whom needs an ephemeral proxy setup  
This may refer to #12
=> feature: Add setup command for Linux and OSX

Makefile, tests/ergo_run_test.go
Fixes #26 
Implemented as an environment variable rather than flag to avoid 'flag not defined' issues.
=> switch integration tests off unless INTEGRATION_TEST environment variable is present

Makefile, appveyor.yml, commands/url.go, make.ps1, tests/ergo_run_test.go
Add integration flag [http://peter.bourgon.org/go-in-production/#testing-and-validation](http://peter.bourgon.org/go-in-production/#testing-and-validation) recommends using the tags for integration. I use the same in my projects. I believe it is clearer. But of course, it is only an option.
Add windows support for testing. 
Add windows make clone.
The make for windows is meant to be run in powershell. 
It follows the same model as linux make (as close as possible).
It was tested on windows 10.
Fix test for url 
Split the tests
=> Work on tests

Makefile, appveyor.yml, make.ps1, proxy/config_test.go, tests/ergo_run_test.go
Solves #34 
Also I've fixed some tests that could cause a second run to fail. This is not visible in Travis or Appveyor, as there every environment is pristine, but when run on the local computer, every time the tests were run, but the first one, they failed.
These tests wrote data to the initial .ergo files.
=> Tests separation

main.go, proxy/config.go, proxy/config_test.go, proxy/proxy_test.go
Gracefully handle case where service declaration has an invalid format.
Fixes https://github.com/cristianoliveira/ergo/issues/32
=> handle invalid declaration format

commands/setup.go, commands/setup_hlp.go, make.ps1, tests/ergo_run_test.go, tests/testCurl.sh
Solves #16 
**Setup test** is written and run for:
- **osx**
- **linux-gnome**
- **windows**
I cannot test **osx**, as I do not have any at my disposal, so, if someone can, please run the tests on mac and fix them as needed.
**Run test** is only written and run for **windows** as windows can use the system proxy using its shell (powershell). (Edit: I've also added tests for **Linux** and **OSX** now)
Perhaps a better approach would be to use chrome headless for example (perhaps even protractor might work). 
Chrome-headless nonetheless would require a chrome installation on the machine, and this is not necessary the case for each development environment.
An unitary approach might be more desirable than a separate one for each environment.
I propose to open a separate issue on this to …
=> Add setup and run tests

Makefile, commands/list.go, make.ps1, proxy/proxy.go
This adds fmt, vet and lint checks for all the tests.
This will make sure that no code that does not respect the Golang
recomended code style will be submited.
This should close #47
=> Add fmt vet lint

appveyor.yml, main.go, proxy/config.go, proxy/proxy.go, tests/ergo_run_test.go, tests/testCurlNotExisting.sh
This addresses #2 
Add basic monitoring of the config file.
The config file is checked for modification (size and modification time) every 500 ms (about twice per second if we ignore the rest of the calculations). If a modification is seen, the services are reloaded.
Possible improvements:
* Possible, at later time, a file modification notification from the OS could be used.
* A lock has been used to ensure that the __services__ are written in a thread safe way. Any latter modification of the __services__ variable of the __config__ should use the same lock.
(Edit) No lock is in use anymore. The synchronisation is done through a channel.
=> Add dynamic configuration reload

main.go, tests/ergo_run_test.go
Solves #52 
I've had to change argument parsing on "setup". Also had to change how ergo was killed (because it was not always killed, so it was running with old configuration)
Comments wellcome :)
I have only tested on Linux, because I don't have Windows or Mac available, but it should work
=> Use a separate temporary config file for testing

proxy/proxy.go, proxy/proxy_test.go
Addresses #61
Test coverage reached 87.3 for proxy.go according to ```go test -cover ./proxy```.
=> Improve test coverage for proxy.go

install.ps1
This solves #59
This install script is the equivalent of the linux/osx install script.
This will install ergo to ```%USERPROFILE%/Ergo/``` and will add it to the ```Path``` environment variable.
The last action is to set an environment variable named ```ERGO_HOME``` that can be later used perhaps to add/access the config file. 
After running this script the user should open a new prompt and will be able to run ergo directly.
=> Add windows install script

main.go, main_test.go
- Moves logic for print out help message to it's own conditional
- Checks length of arguments to the main command before building
subcommands and returns nil if none provided
- Prints usage and returns non-zero exit code if incorrect command is
attempted
Resolves #64
=> Adds error when running ergo without a command

commands/run.go, main.go, main_test.go
these changes should make it possible to change the default `.dev` domain to whatever you want
resolves #70
=> Adds flag for changing the default domain`.dev`

commands/add_service_test.go, commands/commands_helper_test.go, commands/list_names_test.go, commands/list_test.go, commands/url_test.go
I made some refactor on command tests. Created a helper function then we can share some functions for setting up the tests.
=> refactor: Simplify tests and share code

Makefile, make.ps1
This mitigates #78 partially. 
This adds dynamic versioning for manual builds. 
This means that builds that happened after v0.2.0 will also have an appended git commit short description.
The releases, being based on tagged commits, will have the exact version (without the short commit).
This is useful to differentiate between releases and intermediary builds.
We can also eliminate the need for .version file if this will be approved.
An manual ```go build ``` will not add a version though, as it still doesn't add it now.
=> Add dynamic versioning

main.go
Hey, I implemented a fix, which was discussed in #78 .
I have read the project's contributing guidelines, where the fifth point says that I need to create tests for my changes. However, version command could not be tested without changing the flag parsing in main() method, hence I skipped that part.
Also, the contributing guidelines say about good commit messages, I looked up latest commits in the repo and came up with something similar.
Hope, I will be of any help for you, guys :smile:
=> fix: Show default version if ldflag not specified

commands/add_service.go, commands/add_service_test.go, main.go, proxy/config.go, tests/ergo_run_test.go
This fix the problem related to adding new services when using a different ergo file (`-config` flag) it wasn't working.
=> fix: AddService command config flag

.travis.yml, Makefile, appveyor.yml, commands/setup_test.go
There is an incompatibility in `go fmt` and `golint` (details here: https://github.com/golang/lint/issues/415) between golang versions so we are dropping the ci building and testing for versions below 1.11
=> [Chore] Drop support to old go versions due incompatibility

.ergo, Makefile, README.md, proxy/config.go, proxy/config_test.go
Allows the /etc/hosts pattern of URL:PORT -> name
or the original ergo pattern of name -> URL:PORT
but the /etc/hosts pattern has precedence.
(cherry picked from commit 732e34dae69c2d5867b4ae65a6d56a5e13e494ee)
=> feat: allows any pair configuration

.ergo, proxy/config.go, proxy/config_test.go
Usage:
Adds a wildcard service
```
*.frontend http://localhost:3000
```
Run ergo and then all requests like:
- http://foo.frontend.dev/
- http://bar.frontend.dev/
- http://doesnmatter.frontend.dev/
Are now redirected to http://localhost:3000
Closes https://github.com/cristianoliveira/ergo/issues/122
=> feat: allows using wildcards for services

.github/workflows/on-release-upload-assets.yml
(cherry picked from commit 4a591c453223791e8354ac20df46525b95139f36)
=> chore: for windows use tag for release
