cristianoliveira/ergo

proxy/proxy.go

The endpoint for listing is 
`localhost:2000/_ergo/list`

feature: Add endpoint for listing services

---

.gitignore
commands/list.go
commands/list_names.go
commands/run.go
commands/setup.go
commands/url.go
main.go
proxy/config.go
proxy/config_test.go
proxy/proxy.go
tests/ergo_run_test.go

- Fixes for go vet
- Fixes for golint (in progress)
- Fixes #20

Golint fixes

---

Makefile
README.md

Add build before test and readme fixes.

Fixes #24 and #25

---

.gitignore
commands/add_service.go
main.go
proxy/config.go
proxy/config_test.go
tests/ergo_run_test.go

I have added command to add a new service with pretty basic test code. Let me know if we should write more tests.

Add service command

---

commands/url.go

Fix protocol prefix

---

appveyor.yml

I found a typo on the building scripts

fix: Fix windows build

---

main.go
main_test.go

I made some refactor in `main.go` in order to improve our coverage metrics. Now it reaches the 87% :)
```
PASS
coverage: 87.8% of statements
ok      _/Users/cristianoliveira/other/ergo     0.012s
```

Tests improve coverage

---

install.sh

As per #54 this will provide the necessary framework.
It does uses bash syntax, but this should be a non-issue in most modern *nix systems

Make install script more flexible and future-proof

---

README.md
install.ps1

Addresses #59 
This adds readme info for windows.
Also ads some small improvements to windows install script

Add windows install to readme

---

commands/add_service_test.go
commands/list_names_test.go
commands/list_test.go
commands/setup.go
commands/setup_test.go
commands/url.go
commands/url_test.go
proxy/config.go

Addresses #61 
This  is adding tests for the commands.
This concludes my work on tests for now 
``` github.com/cristianoliveira/ergo/commands       1.455s  coverage: 77.8% of statements```
🍾 
You are invited to continue

Add commands tests

---

CONTRIBUTING.md
commands/add_service_test.go
commands/list_names.go
commands/list_names_test.go
commands/list_test.go
commands/remove.go
commands/remove_test.go
commands/url_test.go
main.go
main_test.go
proxy/config.go
proxy/config_test.go
tests/.ergo
tests/ergo_run_test.go

Remove command added with various tests #74

Added remove command

---

commands/add_service.go
commands/add_service_test.go
commands/command.go
commands/list.go
commands/list_names.go
commands/list_names_test.go
commands/list_test.go
commands/remove.go
commands/remove_test.go
commands/run.go
commands/run_test.go
commands/setup.go
commands/url.go
commands/url_test.go
main.go
main_test.go
tests/ergo_run_test.go

Add a common interface for ergo commands

refactor: Add command interface

---

commands/setup.go
commands/setup/configurator.go
commands/setup/linux_configurator.go
commands/setup/osx_configurator.go
commands/setup/runner.go
commands/setup/system_unix.go
commands/setup/system_windows.go
commands/setup/windows_configurator.go
commands/setup_test.go
main.go
proxy/config.go
tests/ergo_run_test.go

Added a runner for setup commands it turns the testing easier

refactor: Add runner for ergo setup

---

main.go
main_test.go
proxy/config.go
proxy/config_test.go

Made so extra refactor in order to ensure that all flags are being parsed and send through config.
Related to #91

fix: Verbose flag not being parsed

---

commands/setup/linux_configurator.go
commands/setup/osx_configurator.go
commands/setup/runner.go
commands/setup/windows_configurator.go
commands/setup_test.go
main_test.go

There was a bad parsing for process commands. I hope with this fix we will solve:
#107 and #105

fix: error linux auto-setup

---

README.md
main.go

readme: explainations for issue #117

---

README.md

ergo is also available via MacPorts.

Mention installation via MacPorts in readme

---

.ergo
commands/add_service_test.go
commands/list_names_test.go
commands/list_test.go
commands/remove.go
commands/remove_test.go
commands/run_test.go
commands/setup_test.go
commands/url_test.go
main.go
main_test.go
proxy/config.go
proxy/config_test.go
proxy/proxy.go
proxy/proxy_test.go
proxy/service.go
proxy/service_test.go
tests/.ergo
tests/ergo_run_test.go

fix: invalid service URL causes unhandled exception

---

main.go
proxy/config.go

fix: confusing error msg for missing/invalid config file

---

.ergo
proxy/config.go
proxy/config_test.go
tests/.ergo
tests/ergo_run_test.go

fix: trim service line before loading
